config_dir: "/var/services"

base_domain: "metrics.kalk.space"

services:
  - traefik
  - prometheus
  - grafana
  - blackbox_exporter
  - unms_exporter
  - ipv6nat
  - unpoller

# Compile list of service specs
service_specs: "{{ lookup('vars', *services) | add_prop_from_list('name', services) }}"

scrape_targets:
  bbb:
    - bbb.kalk.space
  blackbox_icmp:
    - gw1.kalk.space
  blackbox_http:
    - https://discuss.kalk.space/srv/status
  unms:
    - kalkspace.unmsapp.com
  stroma_streama:
    - marcus.stromaproxy.kalk.space
  getraenkekasse:
    - getraenkekasse.kalk.space

prometheus_jobs_extra:
  - job_name: bigbluebutton
    scheme: https
    metrics_path: /metrics/
    basic_auth:
      username: "metrics"
      password: "{{ bbb_metrics_token }}"
    static_configs:
      - targets: "{{ scrape_targets.bbb }}"
  - job_name: stroma-streama
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: "{{ scrape_targets.stroma_streama }}"
  - job_name: getraenkekasse
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: "{{ scrape_targets.getraenkekasse }}"
