# Compiles job definitions from different services
services_except_prometheus: "{{ services | difference(['prometheus']) }}"
prometheus_jobs: "{{ lookup('vars', *services_except_prometheus) | selectattr('jobs','defined') | map(attribute='jobs') | flatten | union(prometheus_jobs_extra) }}"

prometheus_config:
  scrape_configs: "{{ prometheus_jobs }}"

prometheus:
  service:
    image: prom/prometheus
    volumes:
      - type: volume
        source: prometheus_data
        target: /prometheus
    command:
      # default arguments from here:
      # https://registry.hub.docker.com/layers/prom/prometheus/latest/images/sha256-df60172c8d9f08cadae1d79bf86525b6426c47873c712ddf0a04ed424a8c1ad4?context=explore
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # default retention time is only 15d :O
      - "--storage.tsdb.retention.time=2y"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.{{ base_domain }}`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"

  volumes:
    prometheus_data: {}

  files:
    - dest: "/etc/prometheus/prometheus.yml"
      content: "{{ prometheus_config | to_yaml }}"
