# Compiles job definitions from different services
services_except_prometheus: "{{ services | difference(['prometheus']) }}"
prometheus_jobs: "{{ lookup('vars', *services_except_prometheus) | selectattr('jobs','defined') | map(attribute='jobs') | flatten | union(prometheus_jobs_extra) }}"

prometheus_config:
  scrape_configs: "{{ prometheus_jobs }}"

prometheus:
  service:
    image: prom/prometheus
    volumes:
      - type: volume
        source: prometheus_data
        target: /prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.{{ base_domain }}`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"

  volumes:
    prometheus_data: {}

  files:
    - dest: "/etc/prometheus/prometheus.yml"
      content: "{{ prometheus_config | to_yaml }}"
