traefik_config:
  api:
    dashboard: true

  providers:
    file:
      filename: /etc/traefik/traefik-routing.yml

    docker:
      watch: true
      exposedByDefault: false

  entrypoints:
    web:
      address: ":80"
      http:
        redirections:
          entrypoint:
            to: websecure
            scheme: https
            permanent: true

    websecure:
      address: ":443"

  certificatesResolvers:
    myresolver:
      acme:
        httpchallenge:
          entrypoint: web
        email: "{{ letsencrypt_email }}"
        # mounted volume
        storage: /letsencrypt/acme.json

traefik_routing:
  http:
    routers:
      api:
        rule: "Host(`traefik.{{ base_domain }}`)"
        service: "api@internal"
        entryPoints: [websecure]
        tls:
          certResolver: myresolver

traefik:
  service:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: letsencrypt_data
        target: /letsencrypt
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  volumes:
    letsencrypt_data: {}

  files:
    - dest: /etc/traefik/traefik.yml
      content: "{{ traefik_config | to_nice_yaml }}"
    - dest: /etc/traefik/traefik-routing.yml
      content: "{{ traefik_routing | to_nice_yaml }}"
